• Go to hell, request, now everything is on https.request | 1.0.8
MegaVasiliy007/sdc-api pull request #17
Opened 2020-02-29 15:05 UTC by vladciphersky

• Больше никаких зависимостей: враппер переписан на `https.request`, который уже есть при установке `node.js`. [ #16 ]
• Для отправки данных POST-запросом через `setAutopost` также используется `querystring`.

2020-03-02 15:34 UTC, vladciphersky commented
### Up

2020-03-03 12:32 UTC, notlancer requested changes

2020-03-03 12:32 UTC, Lancer8883 commented on sdc.js
> +	var { stringify } = require('querystring');
unusual var

2020-03-03 12:32 UTC, Lancer8883 commented on sdc.js
> +	var { request } = require('https');
unusual var

2020-03-03 12:32 UTC, Lancer8883 commented on sdc.js
> +			var req = request(params, (res) => {
unusual var

2020-03-03 12:49 UTC, vladciphersky commented on sdc.js
> +			var req = request(params, (res) => {
Ok, i'm retarded. Again.

2020-03-14 11:01 UTC, merged